steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build' , '-t' , 'gcr.io/test-395405/apache-webserver-image' , '.']

  # Docker PUSH
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-395405/apache-webserver-image' ]

# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'web-server', '--image', 'gcr.io/test-395405/apache-webserver-image', '--region', 'asia-east1' , '--port' , '80' , '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY